//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendasDBEntities : DbContext
    {
        public VendasDBEntities()
            : base("name=VendasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_FORNECEDOR> TB_FORNECEDOR { get; set; }
        public virtual DbSet<TB_MATERIAL> TB_MATERIAL { get; set; }
        public virtual DbSet<TB_TIPO> TB_TIPO { get; set; }
        public virtual DbSet<TB_VENDA> TB_VENDA { get; set; }
    }
}
