//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FORNECEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_FORNECEDOR()
        {
            this.TB_MATERIAL = new HashSet<TB_MATERIAL>();
            this.TB_VENDA = new HashSet<TB_VENDA>();
        }
    
        public int id { get; set; }
        public string forn_nome { get; set; }
        public string forn_fone { get; set; }
        public string forn_cidade { get; set; }
        public string forn_endereco { get; set; }
        public int forn_cnpj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MATERIAL> TB_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENDA> TB_VENDA { get; set; }
    }
}
