//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MATERIAL()
        {
            this.TB_VENDA = new HashSet<TB_VENDA>();
        }
    
        public int id { get; set; }
        public string mat_desc { get; set; }
        public System.DateTime data_ent { get; set; }
        public int id_tipo { get; set; }
        public decimal mat_valor { get; set; }
        public int id_forn { get; set; }
    
        public virtual TB_FORNECEDOR TB_FORNECEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENDA> TB_VENDA { get; set; }
        public virtual TB_TIPO TB_TIPO { get; set; }
    }
}
