//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVendas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda
    {
        public int id { get; set; }
        public int id_fornec { get; set; }
        public int id_cli { get; set; }
        public int id_mat { get; set; }
        public System.DateTime venda_data { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
        public virtual tb_material tb_material { get; set; }
    }
}
